#!/bin/bash
killall Cydia_
set -e
rsync -SPaz --copy-links saurik@carrier.saurik.com:menes/cydia/cydia_iphoneos-arm.deb .
dpkg -i cydia_iphoneos-arm.deb
touch /tmp/cydia.log
chown mobile.mobile /tmp/cydia.log
openURL "${1-cydia://}"
exec tail /tmp/cydia.log -fn0
